title:              Karan Jogi
email:              kjogi2@uic.edu
description:        Welcome to my portfolio
author:             Karan Jogi
baseurl:            ""
url:                "https://karanjogi.github.io"

# Social Profiles
github_username:  karanjogi
linkedin_username: karan-jogi-70ba49161

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
